title: Chuks Chiazor
logo: /Pages/utils/3.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal

navigation:
  - title: "Home"
    url: "/"
  - title: "Presentations and Articles"
    url: "/presentations-and-articles/"
  - title: "About me"
    url: "/about-me/"

